name: 'Deploy App'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Ping Server
        uses: tyrrrz/action-http-request@master
        with:
          url: https://api.phazed.xyz/api/update?key=${{ secrets.MASTER_KEY }}
